### ISSUE TITLE
🐛Add installation instructions for Ubuntu users

### ISSUE THREAD

**Issue by rsbaher1** [AnjaSlama/Pedestrian-Safety-Reporting#7]
While trying to install the project, errors occurred on the ubuntu 20 system.
These are the steps followed to get it working:  
- install package to get virtual env: `sudo apt install python3.8-venv`  
- install wheel package to build Flask-Bcrtpy: `sudo apt-get install python3-wheel`  
- create new virtual env called venv: `python3 -m venv venv`  
- activate venv: `source venv/bin/activate`
- install wheel before installing requirements.txt: `pip install wheel`
- install requirements: `pip install -r requirements.txt`  
- set env variable: `export FLASK_CONFIG=development`  
- start app: `python app.py runserver`

**Comment by AnjaSlama** [comment]
It would be great if you could update the ReadMe file
